### ISSUE TITLE
UnboundLocalError: local variable 'x' referenced before assignment

### ISSUE THREAD

**Issue by Liampour** [movingforward100/Dehazing_R#3]
Hello,
when I tried to run the models for an image with dimensions  2565x1516 the following error appeared:
```
cuda:0
conv_head.0.weight
conv_head.1.0.weight
conv_head.1.0.bias
conv_head.1.0.running_mean
conv_head.1.0.running_var
conv_head.1.0.num_batches_tracked
head.weight
head.bias
Loading FlashInterimage success
loading dehazing_model success
--- MyEnsembleNet loaded ---
```
```
Traceback (most recent call last):
  File "test.py", line 56, in <module>
    frame_out = MyEnsembleNet(hazy, testing=True)
  File "/home/username/anaconda3/envs/envir38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/username/Dehazing_R/model.py", line 76, in forward
    return x
UnboundLocalError: local variable 'x' referenced before assignment
```

Do I need to modify the code somehow to accept different image dimensions other than 4000x6000?

**Comment by JHX-1997** [comment]
Hello friend, may I ask if you have successfully downloaded these four datasets?

**Comment by Liampour** [comment]
Hello, 
I didn't download the datasets.
I tried to test the code with included images but the dimensions of the images are 4000x6000 and a GPU with more memory than mine is needed to run the model. (My GPU has 6GB memory). So I tried to test the model with smaller sized images.

**Comment by JHX-1997** [comment]
i can help you



---Original---
From: ***@***.***&gt;
Date: Sat, Dec 28, 2024 18:01 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [movingforward100/Dehazing_R] UnboundLocalError: local variable'x' referenced before assignment (Issue #3)




 
Hello,
 I didn't download the datasets.
 I tried to test the code with included images but the dimensions of the images are 4000x6000 and a GPU with more memory than mine is needed to run the model. (My GPU has 6GB memory). So I tried to test the model with smaller sized images.

**Comment by Liampour** [comment]
Do you have any suggestions on what I should do??

**Comment by JHX-1997** [comment]
I suggest you crop the image to 128 by 128, and then set it smaller in batch



---Original---
From: ***@***.***&gt;
Date: Sat, Dec 28, 2024 19:14 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [movingforward100/Dehazing_R] UnboundLocalError: local variable'x' referenced before assignment (Issue #3)




 
Do you have any suggestions on what I need to do??

**Comment by JHX-1997** [comment]
I suggest you crop the image to 128 by 128, and then set it smaller in batch






---Original---
From: ***@***.***&gt;
Date: Sat, Dec 28, 2024 19:14 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [movingforward100/Dehazing_R] UnboundLocalError: local variable'x' referenced before assignment (Issue #3)




 
Do you have any suggestions on what I need to do??

**Comment by Liampour** [comment]
Hello, I am using the `test.py` file but the same error appears. I thinks its because in `model.py` the forward function for testing mode has been designed only for 4000x6000 images (`model.py` line 30-66)

**Comment by LBocheng** [comment]
Hello
I am facing the same problem as you. Have you resolved it?

> Hello, I am using the `test.py` file but the same error appears. I thinks its because in `model.py` the forward function for testing mode has been designed only for 4000x6000 images (`model.py` line 30-66)

**Comment by qiaoukule** [comment]
You can try to use images that are multiples of 16×16 in size. Secondly, i add a code for conditions other than hazy.shape[2] == 4000 and hazy.shape[2] == 6000 in order to run my own test images. I think the dehazing effect is satisfactory.
